
###
//Login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"el@gmail.com",
    "password":"sukses"   
}

//ME
###
GET http://localhost:5000/me
###
//Logout
DELETE http://localhost:5000/logout




###
//getAllProduct
GET http://localhost:5000/products
###
//get Single Product
GET http://localhost:5000/product/76fa7e96-ddfa-4c68-9728-560d4d346d94

###
//Create Product
POST  http://localhost:5000/product
Content-Type: application/json

{
    "name":"Hp Samsung",
   "price": 1250
}

###
PATCH http://localhost:5000/product/63e84c97-6198-4b2b-a956-c483ee63ad73
Content-Type: application/json

{
    "name":"Product eur updated",
   "price": 4150
}

###

DELETE http://localhost:5000/product/0ac0e3cd-44f3-448b-b826-ad9dd1cee17b